version: '3.8'

services:
  app:
    container_name: app
    build: .
    image: moebooru:latest
    # volumes:
    #   - .:/moebooru
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - memcached

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=imouto

  memcached:
    image: memcached:1.6.8-alpine
    container_name: memcached
