# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: imouto
      memcached:
        image: memcached:latest
        ports: ['11211:11211']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
          yarn install
          bundle install
      - name: Setup DB
        run: |
          mkdir -p public/data
          cp config/database.yml.example config/database.yml
          cat <<EOF > config/local_config.rb
          CONFIG["server_host"] = "localhost"
          CONFIG["admin_contact"] = "webmaster@#{CONFIG["server_host"]}"
          CONFIG["memcache_servers"] = ["127.0.0.1:11211"]
          EOF
          bundle exec rails db:create --trace
      - name: Run tests
        run: bundle exec rake
